[theme]
primaryColor = "#2ecc71"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#212529"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "info"
